name: vuepress - CI
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: stritti/kostal-pv-monitor
          TARGET_LINK: //stritti.github.io/kostal-pv-monitor/
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: npm ci && npm run docs:build
          BUILD_DIR: docs/.vuepress/dist/
